### ISSUE TITLE
How to deal with async process in workbox.routing.registerRoute

### ISSUE THREAD

**Issue by liveangela** [liveangela/QALog#5]
**Description**
As the [official document](https://developers.google.com/web/tools/workbox/modules/workbox-routing) told, the main usage is just like
`workbox.routing.registerRoute(matchCb, handlerCb);`

where
> The only limitation is that "match" must synchronously return a truthy value, you can’t perform any asynchronous work. The reason for this is that the Router must synchronously respond to the fetch event or allow falling through to other fetch events.
> The "handler" callback should return a Promise that resolves to a Response.

Sometimes we wish to do some async things in "handler", such as `event.request.json()`.
But it seems to get error when `handlerCb` being an async function.

**Environment**
- workbox-sw: 3+

**Comment by liveangela** [comment]
Firstly, remember that the "handler" should always return a Response object.
Secondly, as shown in the offical document
```js
const handlerCb = ({url, event, params}) => {
  return fetch(event.request)
  .then((response) => {
    return response.text();
  })
  .then((responseBody) => {
    return new Response(`${responseBody} <!-- Look Ma. Added Content. -->`);
  });
};
```
we could definetly write mine like this
```js
const handlerCb = ({url, event, params}) => {
  return event.request().json().then((body) => {
    return new Response(JSON.stringify(body)); // assume body is an object
  });
};
```

**Comment by ghost** [comment]
@liveangela
I want to make use of async code inside the match callback function like below 

`registerRoute(
    async ({ request, url, event, sameOrigin }) => {
        let body = await request.clone().json()
        return body.operationName === 'GetBooks'
    },
    async ({ event }) => staleWhileRevalidate(event),
    'POST'
);`

I want this router handler to not execute if the "operationName" inside the body is not "GetBooks" and I want a different registerRoute functions to handle different "operationNames". I am using graphql and all the network requests are of type 'POST' when using graphql

Could you pls help?
